corpusDir: "coverage"
testLimit: 10000
# seqLen: 100
# shrinkLimit:
cryticArgs:
  [
    "--solc-remaps",
    "@openzeppelin/contracts/=../../../../lib/openzeppelin-contracts/contracts/ forge-std/=../../../../lib/forge-std/src/",
  ]
