echidna-overflow:
	echidna --config config-overflow.yaml ./BondCurveTokenWrapper.sol --contract BondCurveTokenWrapper

echidna-property:
	echidna --config config.yaml ./BondCurveTokenWrapper.sol --contract BondCurveTokenWrapper